import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import VerticalNavbar from '@/components/Navbar';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <div className="relative parent h-screen p-10">
      <div className="absolute inset-0 bg-cover bg-black bg-center" style={{ backgroundImage: "url('/your-background-image.jpg')" }} />
                    
      <div className="relative child h-full flex rounded-lg">
        <VerticalNavbar />

        <div className="flex-grow bg-white">
          {children}
        </div>
      </div>
    </div>
    </body>
    </html>
  );
}
